[package]
name = "quick-init"
author = "Oscar Pickerill <me@oscars.dev>"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
spinners = "4.1.0"
